<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-US9O7O0" name="com.dsalgo.qa.testcases.MainPageAndLoginTest" tests="5" failures="1" timestamp="2022-05-16T11:10:41 PDT" time="35.424" errors="0">
  <testcase name="verifyLogin" time="7.108" classname="com.dsalgo.qa.testcases.MainPageAndLoginTest"/>
  <system-out/>
  <testcase name="successfulLogin" time="5.052" classname="com.dsalgo.qa.testcases.MainPageAndLoginTest">
    <skipped/>
  </testcase> <!-- successfulLogin -->
  <system-out/>
  <testcase name="verifyLogin" time="6.866" classname="com.dsalgo.qa.testcases.MainPageAndLoginTest"/>
  <system-out/>
  <testcase name="successfulLogin" time="11.585" classname="com.dsalgo.qa.testcases.MainPageAndLoginTest">
    <skipped/>
  </testcase> <!-- successfulLogin -->
  <system-out/>
  <testcase name="successfulLogin" time="4.813" classname="com.dsalgo.qa.testcases.MainPageAndLoginTest">
    <failure type="java.lang.AssertionError" message="expected [Numpy Ninja5] but found [Numpy Ninja]">
      <![CDATA[java.lang.AssertionError: expected [Numpy Ninja5] but found [Numpy Ninja]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.dsalgo.qa.testcases.MainPageAndLoginTest.successfulLogin(MainPageAndLoginTest.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- successfulLogin -->
  <system-out/>
</testsuite> <!-- com.dsalgo.qa.testcases.MainPageAndLoginTest -->
